### ISSUE TITLE
Move source into specific packages

### ISSUE THREAD

**Issue by pipeaesac** [SeeBenj/JGeoTile#4]
Sources and test code is currently located in default packages. This should be moved to specifically named packages, such as `ch.hsr.ifs.jgeotile`.

**Comment by pipeaesac** [comment]
The packaging for the test cases was fixed. However, the sources of the library should be put in a "Source Folder" called `src` and then moved to specifically named packages, such as `ch.hsr.ifs.jgeotile`.

**Comment by SeeBenj** [comment]
moved to src
